package skillsrc

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCLIInitCreatesProjectFilesWithoutLock(t *testing.T) {
	home := t.TempDir()
	root := filepath.Join(home, "project")
	require.NoError(t, os.MkdirAll(root, 0o755))
	writeTestFile(t, filepath.Join(root, ".gitignore"), "keep/\n")
	var out, stderr bytes.Buffer
	runtime := scopeRuntime(root, home)
	runtime.Out, runtime.Err = &out, &stderr

	assert.Equal(t, 0, RunCLI(context.Background(), []string{"init"}, runtime), stderr.String())
	assert.Equal(t, "  ✓ "+filepath.Join("~", "project", "skills.toml")+" · initialized\n", out.String())
	manifest, err := os.ReadFile(filepath.Join(root, "skills.toml"))
	require.NoError(t, err)
	assert.Equal(t, "version = 1\n", string(manifest))
	assert.NoFileExists(t, filepath.Join(root, "skills.lock"))
	rootIgnore, err := os.ReadFile(filepath.Join(root, ".gitignore"))
	require.NoError(t, err)
	assert.Equal(t, "keep/\n# skillsrc runtime\n/.agents/.gitignore\n", string(rootIgnore))
	managed, err := os.ReadFile(filepath.Join(root, ".agents", ".gitignore"))
	require.NoError(t, err)
	assert.Equal(t, "# Generated by skillsrc. Do not edit.\n/skills/.skillsrc-*\n", string(managed))

	stderr.Reset()
	assert.Equal(t, 1, RunCLI(context.Background(), []string{"init"}, runtime))
	assert.Equal(t, "Error: project is already initialized at \"~/project/skills.toml\"\n", stderr.String())
}

func TestDisplayPathOnlyShortensPathsWithinHome(t *testing.T) {
	t.Parallel()
	home := filepath.Join(string(filepath.Separator), "Users", "person")
	assert.Equal(t, "~", displayPath(home, home))
	assert.Equal(t, filepath.Join("~", "project", "skills.toml"), displayPath(filepath.Join(home, "project", "skills.toml"), home))
	assert.Equal(t, filepath.Join(string(filepath.Separator), "opt", "project", "skills.toml"), displayPath(filepath.Join(string(filepath.Separator), "opt", "project", "skills.toml"), home))
}

func TestHumanPathDisplayShortensErrorsAndLocalSources(t *testing.T) {
	t.Parallel()
	home := filepath.Join(string(filepath.Separator), "Users", "person")
	path := filepath.Join(home, "project", "skills.toml")
	assert.Equal(t, `open "~/project/skills.toml": denied`, displayPathsInText(`open "`+path+`": denied`, home))
	assert.Equal(t, "~/project/skills.toml", displaySource(path, home))
	assert.Equal(t, "file://"+path, displayPathsInText("file://"+path, home))
}

func TestCLIUserAliasesSelectOnlyUserManifest(t *testing.T) {
	home := t.TempDir()
	cwd := filepath.Join(home, "project")
	require.NoError(t, os.MkdirAll(cwd, 0o755))
	writeTestFile(t, filepath.Join(home, ".agents", "skills.toml"), "version = 1\n")
	writeTestFile(t, filepath.Join(cwd, "skills.toml"), "invalid = true\n")
	for _, alias := range []string{"-g", "--global", "--user"} {
		alias := alias
		t.Run(alias, func(t *testing.T) {
			var out, stderr bytes.Buffer
			runtime := scopeRuntime(cwd, home)
			runtime.Out, runtime.Err = &out, &stderr
			assert.Equal(t, 0, RunCLI(context.Background(), []string{alias, "list"}, runtime), stderr.String())
			assert.Contains(t, out.String(), "0 skills")
		})
	}
}

func TestCLIManifestConflictIsUsageError(t *testing.T) {
	home := t.TempDir()
	var stderr bytes.Buffer
	runtime := scopeRuntime(home, home)
	runtime.Err = &stderr
	code := RunCLI(context.Background(), []string{"--global", "--manifest", "x", "sync"}, runtime)
	assert.Equal(t, 2, code)
	assert.Contains(t, stderr.String(), "cannot be combined")
}

func TestHelpUsesCommandOrientedLayout(t *testing.T) {
	t.Parallel()
	var output bytes.Buffer
	printUsage(&output)
	help := output.String()
	assert.Contains(t, help, "Usage: skillsrc [OPTIONS] <COMMAND>\n")
	assert.Contains(t, help, "Commands:\n  init      Initialize a manifest")
	assert.Contains(t, help, "Scope selection:\n")
	assert.Contains(t, help, "Options:\n")
	assert.NotContains(t, help, "[global flags]")
	assert.Equal(t, 1, strings.Count(help, "Usage:"))

	for _, flag := range []string{"-h", "--help"} {
		var stdout, stderr bytes.Buffer
		runtime := scopeRuntime(t.TempDir(), t.TempDir())
		runtime.Out, runtime.Err = &stdout, &stderr
		assert.Equal(t, 0, RunCLI(context.Background(), []string{flag}, runtime))
		assert.Contains(t, stdout.String(), "Commands:")
		assert.Empty(t, stderr.String())
	}
}

func TestCLIClassifiesCommandsBeforeDiscovery(t *testing.T) {
	home := t.TempDir()
	cwd := filepath.Join(home, "empty")
	require.NoError(t, os.MkdirAll(cwd, 0o755))
	var out, stderr bytes.Buffer
	runtime := scopeRuntime(cwd, home)
	runtime.Out, runtime.Err = &out, &stderr

	assert.Equal(t, 0, RunCLI(context.Background(), []string{"help"}, runtime))
	assert.NotContains(t, out.String(), "no project skills.toml")
	stderr.Reset()
	assert.Equal(t, 2, RunCLI(context.Background(), []string{"unknown"}, runtime))
	assert.NotContains(t, stderr.String(), "no project skills.toml")
	stderr.Reset()
	assert.Equal(t, 2, RunCLI(context.Background(), nil, runtime))
	assert.NotContains(t, stderr.String(), "no project skills.toml")
}

func TestCLIProjectDiscoveryDoesNotTreatUserManifestAsProject(t *testing.T) {
	home := t.TempDir()
	userRoot := filepath.Join(home, ".agents")
	cwd := filepath.Join(userRoot, "nested")
	local := filepath.Join(home, "source")
	require.NoError(t, os.MkdirAll(cwd, 0o755))
	makeSkill(t, filepath.Join(local, "one"), "one", "body")
	writeTestFile(t, filepath.Join(userRoot, "skills.toml"), "version = 1\n[[sources]]\npath = \"../source\"\nskills = [\"one\"]\n")
	var stderr bytes.Buffer
	runtime := scopeRuntime(cwd, home)
	runtime.Err = &stderr

	assert.Equal(t, 1, RunCLI(context.Background(), []string{"sync"}, runtime))
	assert.Contains(t, stderr.String(), "no project skills.toml found")
	assert.NoDirExists(t, filepath.Join(userRoot, ".agents"))

	stderr.Reset()
	assert.Equal(t, 0, RunCLI(context.Background(), []string{"-g", "sync"}, runtime), stderr.String())
	assert.FileExists(t, filepath.Join(userRoot, "skills", "one", "SKILL.md"))
	assert.NoDirExists(t, filepath.Join(userRoot, ".agents"))
}

func TestCLIProjectDiscoveryFromNestedDirectoryWritesManagedMetadata(t *testing.T) {
	home := t.TempDir()
	root := filepath.Join(home, "project")
	cwd := filepath.Join(root, "nested")
	local := filepath.Join(root, "source")
	require.NoError(t, os.MkdirAll(cwd, 0o755))
	makeSkill(t, filepath.Join(local, "one"), "one", "body")
	writeTestFile(t, filepath.Join(root, "skills.toml"), "version = 1\n[[sources]]\npath = \"./source\"\nskills = [\"one\"]\n")
	require.NoError(t, EnsureRootGitignore(root))
	var out, stderr bytes.Buffer
	runtime := scopeRuntime(cwd, home)
	runtime.Out, runtime.Err = &out, &stderr

	assert.Equal(t, 0, RunCLI(context.Background(), []string{"sync"}, runtime), stderr.String())
	assert.FileExists(t, filepath.Join(root, "skills.lock"))
	assert.FileExists(t, filepath.Join(root, ".agents", "skills", "one", "SKILL.md"))
	managed, err := os.ReadFile(filepath.Join(root, ".agents", ".gitignore"))
	require.NoError(t, err)
	assert.Contains(t, string(managed), "/skills/one/\n")
}

func TestCLIExplicitManifestDoesNotWriteProjectMetadata(t *testing.T) {
	home := t.TempDir()
	cwd := filepath.Join(home, "work")
	explicitRoot := filepath.Join(home, "config")
	require.NoError(t, os.MkdirAll(cwd, 0o755))
	writeTestFile(t, filepath.Join(explicitRoot, "skills.toml"), "version = 1\n")
	var stderr bytes.Buffer
	runtime := scopeRuntime(cwd, home)
	runtime.Err = &stderr

	assert.Equal(t, 0, RunCLI(context.Background(), []string{"--manifest", filepath.Join(explicitRoot, "skills.toml"), "sync"}, runtime), stderr.String())
	assert.NoFileExists(t, filepath.Join(explicitRoot, ".gitignore"))
	assert.NoFileExists(t, filepath.Join(explicitRoot, ".agents", ".gitignore"))
}
