package skillsrc

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	rootGitignoreHeader       = "# skillsrc runtime"
	rootManagedIgnoreFileRule = "/.agents/.gitignore"
	managedGitignoreHeader    = "# Generated by skillsrc. Do not edit."
)

var rootGitignoreRules = []string{rootManagedIgnoreFileRule}

// InitializeManifest creates a minimal version-one manifest without replacing an
// existing file.
func InitializeManifest(path string) error {
	data, err := EncodeManifest(Manifest{Version: SchemaVersion})
	if err != nil {
		return err
	}
	if err := writeAtomicNew(path, data, 0o644); err != nil {
		if errors.Is(err, os.ErrExist) {
			return fmt.Errorf("initialize manifest %q: file already exists", path)
		}
		return fmt.Errorf("initialize manifest %q: %w", path, err)
	}
	return nil
}

// EnsureRootGitignore adds the project runtime rules while preserving all
// existing content.
func EnsureRootGitignore(root string) error {
	path := filepath.Join(root, ".gitignore")
	current, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read root .gitignore: %w", err)
	}

	present := gitignoreLines(current)
	missing := make([]string, 0, len(rootGitignoreRules))
	for _, rule := range rootGitignoreRules {
		if _, ok := present[rule]; !ok {
			missing = append(missing, rule)
		}
	}
	_, headerPresent := present[rootGitignoreHeader]
	if headerPresent && len(missing) == 0 {
		return nil
	}

	updated := append([]byte(nil), current...)
	if len(updated) > 0 && updated[len(updated)-1] != '\n' {
		updated = append(updated, '\n')
	}
	if !headerPresent {
		updated = append(updated, rootGitignoreHeader...)
		updated = append(updated, '\n')
	}
	for _, rule := range missing {
		updated = append(updated, rule...)
		updated = append(updated, '\n')
	}
	if err := writeAtomic(path, updated, 0o644); err != nil {
		return fmt.Errorf("write root .gitignore: %w", err)
	}
	return nil
}

// WriteManagedGitignore writes the generated ignore file for the skills named
// by the lock. It deliberately does not ignore the entire skills directory.
func WriteManagedGitignore(root string, lock Lock) error {
	data, err := managedGitignore(lock)
	if err != nil {
		return err
	}
	path := filepath.Join(root, ".agents", ".gitignore")
	if err := writeAtomic(path, data, 0o644); err != nil {
		return fmt.Errorf("write managed .gitignore: %w", err)
	}
	return nil
}

// CheckProjectFiles reports missing or stale project ignore metadata.
func CheckProjectFiles(root string, lock Lock) ([]DoctorIssue, error) {
	issues := make([]DoctorIssue, 0)
	rootPath := filepath.Join(root, ".gitignore")
	rootData, err := os.ReadFile(rootPath)
	if errors.Is(err, os.ErrNotExist) {
		issues = append(issues, DoctorIssue{Kind: "project", Message: "root .gitignore is missing skillsrc runtime entries"})
	} else if err != nil {
		return nil, fmt.Errorf("read root .gitignore: %w", err)
	} else {
		present := gitignoreLines(rootData)
		if _, ok := present[rootGitignoreHeader]; !ok {
			issues = append(issues, DoctorIssue{Kind: "project", Message: "root .gitignore is missing the skillsrc runtime header"})
		}
		for _, rule := range rootGitignoreRules {
			if _, ok := present[rule]; !ok {
				issues = append(issues, DoctorIssue{Kind: "project", Message: fmt.Sprintf("root .gitignore is missing %s", rule)})
			}
		}
	}

	expected, err := managedGitignore(lock)
	if err != nil {
		return nil, err
	}
	managedPath := filepath.Join(root, ".agents", ".gitignore")
	actual, err := os.ReadFile(managedPath)
	if errors.Is(err, os.ErrNotExist) {
		issues = append(issues, DoctorIssue{Kind: "project", Message: ".agents/.gitignore is missing"})
	} else if err != nil {
		return nil, fmt.Errorf("read managed .gitignore: %w", err)
	} else if string(actual) != string(expected) {
		issues = append(issues, DoctorIssue{Kind: "project", Message: ".agents/.gitignore is stale"})
	}
	return issues, nil
}

func managedGitignore(lock Lock) ([]byte, error) {
	names := make([]string, 0)
	seen := make(map[string]struct{})
	for _, source := range lock.Sources {
		for _, skill := range source.Skills {
			if !skillNamePattern.MatchString(skill.Name) || skill.Name == "." || skill.Name == ".." {
				return nil, fmt.Errorf("generate managed .gitignore: invalid skill name %q", skill.Name)
			}
			if _, ok := seen[skill.Name]; ok {
				continue
			}
			seen[skill.Name] = struct{}{}
			names = append(names, skill.Name)
		}
	}
	sort.Strings(names)

	var builder strings.Builder
	builder.WriteString(managedGitignoreHeader)
	builder.WriteByte('\n')
	builder.WriteString("/skills/.skillsrc-*\n")
	for _, name := range names {
		fmt.Fprintf(&builder, "/skills/%s/\n", name)
	}
	return []byte(builder.String()), nil
}

func gitignoreLines(data []byte) map[string]struct{} {
	lines := make(map[string]struct{})
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSuffix(line, "\r")
		lines[line] = struct{}{}
	}
	return lines
}
