package skillsrc

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestInitializeManifestCreatesMinimalManifestAndPreservesExisting(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	path := filepath.Join(root, "nested", "skills.toml")

	if err := InitializeManifest(path); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := string(data), "version = 1\n"; got != want {
		t.Fatalf("manifest = %q, want %q", got, want)
	}

	if err := InitializeManifest(path); err == nil {
		t.Fatal("InitializeManifest() overwrote an existing manifest")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(data) {
		t.Fatalf("existing manifest changed to %q", after)
	}
}

func TestInitializeManifestPublishesOnceUnderConcurrency(t *testing.T) {
	t.Parallel()
	path := filepath.Join(t.TempDir(), "skills.toml")
	start := make(chan struct{})
	results := make(chan error, 8)
	for range 8 {
		go func() {
			<-start
			results <- InitializeManifest(path)
		}()
	}
	close(start)
	succeeded := 0
	for range 8 {
		if err := <-results; err == nil {
			succeeded++
		}
	}
	if succeeded != 1 {
		t.Fatalf("successful initializers = %d, want 1", succeeded)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if got, want := string(data), "version = 1\n"; got != want {
		t.Fatalf("manifest = %q, want %q", got, want)
	}
}

func TestEnsureRootGitignorePreservesContentAndIsIdempotent(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	path := filepath.Join(root, ".gitignore")
	original := []byte("vendor/\n# keep this\n/.skillsrc-install.lock")
	if err := os.WriteFile(path, original, 0o644); err != nil {
		t.Fatal(err)
	}

	if err := EnsureRootGitignore(root); err != nil {
		t.Fatal(err)
	}
	want := "vendor/\n# keep this\n/.skillsrc-install.lock\n# skillsrc runtime\n/.agents/.gitignore\n"
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := string(data); got != want {
		t.Fatalf(".gitignore = %q, want %q", got, want)
	}
	if err := EnsureRootGitignore(root); err != nil {
		t.Fatal(err)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := string(after); got != want {
		t.Fatalf("second .gitignore = %q, want %q", got, want)
	}
}

func TestEnsureRootGitignoreCreatesExactContent(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	if err := EnsureRootGitignore(root); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# skillsrc runtime\n/.agents/.gitignore\n"
	if got := string(data); got != want {
		t.Fatalf(".gitignore = %q, want %q", got, want)
	}
}

func TestWriteManagedGitignoreIsExactSortedAndIncludesAllSourceKinds(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	lock := Lock{Version: SchemaVersion, Sources: []LockSource{
		{Kind: SourceLocal, Skills: []LockedSkill{{Name: "zeta"}, {Name: "beta"}}},
		{Kind: SourceGit, Skills: []LockedSkill{{Name: "alpha"}}},
	}}
	if err := WriteManagedGitignore(root, lock); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".agents", ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by skillsrc. Do not edit.\n" +
		"/skills/.skillsrc-*\n" +
		"/skills/alpha/\n" +
		"/skills/beta/\n" +
		"/skills/zeta/\n"
	if got := string(data); got != want {
		t.Fatalf("managed .gitignore = %q, want %q", got, want)
	}
	if err := WriteManagedGitignore(root, lock); err != nil {
		t.Fatal(err)
	}
	after, err := os.ReadFile(filepath.Join(root, ".agents", ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != want {
		t.Fatalf("second managed .gitignore = %q, want %q", after, want)
	}
}

func TestCheckProjectFilesReportsAndClearsMissingAndStaleMetadata(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	lock := Lock{Version: SchemaVersion, Sources: []LockSource{{Skills: []LockedSkill{{Name: "one"}}}}}

	issues, err := CheckProjectFiles(root, lock)
	if err != nil {
		t.Fatal(err)
	}
	wantMissing := []DoctorIssue{
		{Kind: "project", Message: "root .gitignore is missing skillsrc runtime entries"},
		{Kind: "project", Message: ".agents/.gitignore is missing"},
	}
	if !reflect.DeepEqual(issues, wantMissing) {
		t.Fatalf("missing issues = %#v, want %#v", issues, wantMissing)
	}

	if err := EnsureRootGitignore(root); err != nil {
		t.Fatal(err)
	}
	rootPath := filepath.Join(root, ".gitignore")
	rootData, err := os.ReadFile(rootPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(rootPath, append(rootData, []byte("/.skillsrc-install.lock\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, ".agents"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".agents", ".gitignore"), []byte("old\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	issues, err = CheckProjectFiles(root, lock)
	if err != nil {
		t.Fatal(err)
	}
	wantStale := []DoctorIssue{{Kind: "project", Message: ".agents/.gitignore is stale"}}
	if !reflect.DeepEqual(issues, wantStale) {
		t.Fatalf("stale issues = %#v, want %#v", issues, wantStale)
	}

	if err := EnsureRootGitignore(root); err != nil {
		t.Fatal(err)
	}
	if err := WriteManagedGitignore(root, lock); err != nil {
		t.Fatal(err)
	}
	issues, err = CheckProjectFiles(root, lock)
	if err != nil {
		t.Fatal(err)
	}
	if len(issues) != 0 {
		t.Fatalf("current metadata issues = %#v", issues)
	}
}
